name: NPM test and package

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Use node v12"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
      NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Use node v12"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # Need an `id` for output variables
        with:
          branch: master
        # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog@3.0.0
