name: NPM test and package

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Use node v12"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
