name: NPM publish

on:
  push:
    branches:
      - releases

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CI: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Use node ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Use node v14"
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          scope: '@oreliain'
      - name: npm install, build
        run: |
          npm ci --ignore-scripts
          npm run build --if-present
      - name: set npm config
        run: |
          echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n@oreliain:registry=https://registry.npmjs.org/\nalways-auth=false" > "$NPM_CONFIG_USERCONFIG"
      - name: Semantic Releaser
        run: npm run release